### ISSUE TITLE
Opens with quotes but closes with curly brace.  Which?

### ISSUE THREAD

**Issue by SamuraiCrow** [GCC-Tiny/gcc-tiny-docs-rtd#12]
https://github.com/GCC-Tiny/gcc-tiny-docs-rtd/blob/part01/docs/source/part01.rst#L57

Just a typo but I don't know Sphinx syntax to know which is right.

**Comment by HSorensen** [comment]
Good catch, this is a leftover from the texi conversion. Will fix.

The line begin with .. with is Sphinx for a comment.
Look at https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html for more details on Sphinx. I am also learning this we go, so don't assume I know what I'm doing.

**Comment by HSorensen** [comment]
Fixed: https://github.com/GCC-Tiny/gcc-tiny-docs-rtd/blob/2a9aaec723ab48562e6c8c523835564c366707e7/docs/source/part01.rst?plain=1#L57

**Comment by HSorensen** [comment]
Cleaned up the left over from texi conversion
